---
title: "Child Patients with Covid-19 and Cystic Fibrosis"
author: "Alfonso Vieyra, Brandon Huett, Allison Cher, Brittnie Villasenor, Ernesto Collazo"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(scales)

# Need to always load the package though
library(epitools)
library(rmeta)
library(pROC)
library(nnet)
```

```{r prop comp}
# This is the prop.comp() function we will use
#######
prop.comp <- function( x, estimate="all", conf.level=.95, transpose=FALSE ){
	if( transpose ) x <- t(x)
	rslt <- vector( "list", length=3 )
	names( rslt ) <- c( "riskdiff", "riskratio", "oddsratio" )
	diff.rslt <- suppressWarnings(prop.test( x, conf.level=conf.level ))
	rslt[[1]] <- rslt[[2]] <- rslt[[3]] <- epitab( x, method="riskratio", pvalue="chi2", conf.level=conf.level )$tab
	colnames( rslt[[1]] )[5] <- "riskdiff"
	rslt[[1]][,5] <- c(0,diff(rev(diff.rslt$estimate)))
	rslt[[1]][2,6:7] <- diff.rslt$conf.int
	colnames( rslt[[3]] )[5] <- "oddsratio"
	rslt[[3]][,5:8] <- suppressWarnings(epitab( x, method="oddsratio", pvalue="chi2", conf.level=conf.level )$tab[,5:8])
	if(is.null(names(dimnames(x)))){
		for(i in 1:3){
			colnames(rslt[[i]])[c(1,3)] <- c("Outcome=0", "Outcome=1")
			rownames(rslt[[i]]) <- c("Group=1", "Group=2")
			}
	}
	if( is.element( estimate, c("all", "oddsratio") ) ){ 
		if(is.null(names(dimnames(x)))){
			warning( "Estimated probabilities represent Pr[ Outcome | Group ]. For estimates of 
			Pr[ Group | Outcome ], change the value of 'transpose'.")
		}
		else
			warning( paste("Estimated probabilities represent Pr[", names(dimnames(x))[2], 
			"|",names(dimnames(x))[1], "]. For estimates of 
			Pr[", names(dimnames(x))[1], "|",names(dimnames(x))[2], "], change the value of 'transpose'.") )
		}
	if( estimate == "riskdiff" ) return(rslt[[1]])
	else if( estimate == "riskratio" ) return(rslt[[2]])
	else if( estimate == "oddsratio" ) return(rslt[[3]])
	else return(rslt)
}
```


## EDA Analysis

```{r morbidity Tables}
#table with severity, cf and comorbidities NOTE: Changed names for readability
morb_df <- d %>%
  select(has_cf, COVIDseverity, starts_with('comorb'))


colnames(morb_df) <- c('has_cf', 'COVIDseverity', 'bronchiectasis',
                        'pulmonary_disease', 'asthma', 'nasal_polyps',
                        'hemoptysis', 'pneumothorax', 'resp_failure', 
                        'malnutrition', 'other_nutri_deficiency', 
                        'type1_diabetes', 'type2_diabetes', 'obesity', 
                        'liver_disease', 'other_GI_notLiver', 
                        'essential_hypertension', 'hypertensive_heart_disease',
                        'chronic_kidney_disease', 'nicotine_dependence', 
                        'heart_failure', 'ischemic_heart_disease', 
                        'lung_transplant')

#table of non cystic fibrosis patients
morb_noCF <- morb_df  %>%
  filter(has_cf == 0)

#table of cystic fibrosis patients
morb_CF <- morb_df %>%
  filter(has_cf == 1)
```

```{r funcy}
#created a function to calculate the proportions in a 1D vector
prop1 <- function(arr, denom) {
  count = 1
  for (x in arr)
  {
    arr[count] = round(x / denom, 2)
    count = count + 1
  }
  return(arr)
}
```

```{r Severity Levels noCF}

#Tables of severity symptoms level 0
severity0_noCF <- morb_noCF %>%
  filter(COVIDseverity == 0) %>%
  select(-has_cf, -COVIDseverity)

indx0 <- sapply(severity0_noCF, is.factor)
severity0_noCF[indx0] <- lapply(severity0_noCF[indx0], 
                           function(x) as.numeric(as.character(x)))

#Tables of severity symptoms level 1
severity1_noCF <- morb_noCF %>%
  filter(COVIDseverity == 1) %>%
  select(-has_cf, -COVIDseverity)

indx1 <- sapply(severity1_noCF, is.factor)
severity1_noCF[indx1] <- lapply(severity1_noCF[indx1], 
                           function(x) as.numeric(as.character(x)))

#Tables of severity symptoms level 2 
severity2_noCF <- morb_noCF %>%
  filter(COVIDseverity == 2) %>%
  select(-has_cf, -COVIDseverity)

indx2 <- sapply(severity2_noCF, is.factor)
severity2_noCF[indx2] <- lapply(severity2_noCF[indx2], 
                           function(x) as.numeric(as.character(x)))

#Vectorized severities of counts
asymptomatic <- colSums(severity0_noCF)
mild_symptoms <- colSums(severity1_noCF)
severe_symptoms <- colSums(severity2_noCF)

#created new df based on counts of morbidities across severity lvls 
library(reshape2)

sev_lvls_noCF <- rbind(asymptomatic, mild_symptoms, severe_symptoms)
sev_lvls_noCF[1, ] <- prop1(sev_lvls_noCF[1,], 296236)
sev_lvls_noCF[2, ] <- prop1(sev_lvls_noCF[2,], 34015)
sev_lvls_noCF[3, ] <- prop1(sev_lvls_noCF[3,], 20743)

melted_sev_lvls_noCF <- melt(sev_lvls_noCF)
colnames(melted_sev_lvls_noCF) <- c('severity_lvl', 'morbidity','proportion')
```


```{r visual non-CF}
options(scipen = 999)
ggplot(melted_sev_lvls_noCF, aes(x=morbidity, y = proportion, fill = proportion)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  labs( x = 'Morbidities', y = 'Total Reported Conditions') +
  ggtitle('Dominant Conditions in Non-CF patients with Covid 19') +
  theme(plot.title = element_text(hjust = 0.5)) +
  facet_wrap(~severity_lvl) + 
  theme(axis.text.x = element_text(angle=45))
```

```{r Severity Levels CF}
#Tables of severity symptoms level 0
severity0_CF <- morb_CF %>%
  filter(COVIDseverity == 0) %>%
  select(-has_cf, -COVIDseverity)

indx0_cf <- sapply(severity0_CF, is.factor)
severity0_CF[indx0_cf] <- lapply(severity0_CF[indx0_cf], 
                           function(x) as.numeric(as.character(x)))

#Tables of severity symptoms level 1
severity1_CF <- morb_CF %>%
  filter(COVIDseverity == 1) %>%
  select(-has_cf, -COVIDseverity)

indx1_cf <- sapply(severity1_CF, is.factor)
severity1_CF[indx1_cf] <- lapply(severity1_CF[indx1_cf], 
                           function(x) as.numeric(as.character(x)))

#Tables of severity symptoms level 2 
severity2_CF <- morb_CF %>%
  filter(COVIDseverity == 2) %>%
  select(-has_cf, -COVIDseverity)

indx2_cf <- sapply(severity2_CF, is.factor)
severity2_CF[indx2_cf] <- lapply(severity2_CF[indx2_cf], 
                           function(x) as.numeric(as.character(x)))

#Vectorized severities of counts
asympt_mild <- colSums(severity0_CF)
moderate_symptoms <- colSums(severity1_CF)
severe_symptoms <- colSums(severity2_CF)

#created new df based on counts of morbidities across severity lvls 
sev_lvls_CF <- rbind(asympt_mild, moderate_symptoms, severe_symptoms)
sev_lvls_CF[1,] <- prop1(sev_lvls_CF[1,], 8454)
sev_lvls_CF[2,] <- prop1(sev_lvls_CF[2,], 1216)
sev_lvls_CF[3,] <- prop1(sev_lvls_CF[3,], 646)

melted_sev_lvls_CF <- melt(sev_lvls_CF)
colnames(melted_sev_lvls_CF) <- c('severity_lvl', 'morbidity','proportion')
```

```{r visual CF}
ggplot(melted_sev_lvls_CF, aes(x=morbidity, y = proportion, fill = proportion)) +
  geom_bar(stat = 'identity') +
  coord_flip()+
  labs( x = 'Morbidities', y = 'Proportion of Conditions') +
  ggtitle('Dominant Conditions in CF patients with Covid 19') +
  theme(plot.title = element_text(hjust = 0.5)) +
  facet_wrap(~severity_lvl) + 
  theme(axis.text.x = element_text(angle=45))
```

```{r cf non cf}
has_CF <- morb_CF %>%
  select(-has_cf, -COVIDseverity)

indx_hasCF <- sapply(has_CF, is.factor)
has_CF[indx_hasCF] <- lapply(has_CF[indx_hasCF], 
                           function(x) as.numeric(as.character(x)))

has_noCF <- morb_noCF %>%
  select(-has_cf, -COVIDseverity)

indx_hasNoCF <- sapply(has_noCF, is.factor)
has_noCF[indx_hasNoCF] <- lapply(has_noCF[indx_hasNoCF], 
                           function(x) as.numeric(as.character(x)))

cyst_fibrosis_patients <- colSums(has_CF)
noncyst_fibrosis_patients <- colSums(has_noCF)

cf_lvls <- rbind(cyst_fibrosis_patients, noncyst_fibrosis_patients)
cf_lvls[1,] <- prop1(cf_lvls[1,], 10316)
cf_lvls[2,] <- prop1(cf_lvls[2,], 350994)

melted_cf_lvls <- melt(cf_lvls)
colnames(melted_cf_lvls) <- c('has_CF', 'morbidity','proportion')
```

```{r visuals cf lvls}
ggplot(melted_cf_lvls, aes(x=morbidity, y = proportion, fill = proportion)) +
  geom_bar(stat = 'identity') +
  coord_flip()+
  labs( x = 'Morbidities', y = 'Proportion of Conditions') +
  ggtitle('Dominant Conditions in CF and non-CF patients with Covid 19') +
  theme(plot.title = element_text(hjust = 0.5)) +
  facet_wrap(~has_CF) + 
  theme(axis.text.x = element_text(angle=45))
```

```{r # of morbidities in patients}
#number of mordidities in each patient
num_morb_perCF <- table(rowSums(has_CF))
num_morb_perNonCF <- table(rowSums(has_noCF))

#Assign proportions for the number of comorbidities per patient
num_morb_perCF <- prop1(num_morb_perCF, 9337)
num_morb_perNonCF <- prop1(num_morb_perNonCF, 916615)
```

## Modeling Proposals

summary(glm(has_cf~comorb_bronchiectasis_J47, family = binomial(link='identity'), data = d))


```{r severity changed}
#created altered data frame of morb_df to have severity to two levels
morb_df_01 <- morb_df
morb_df_01['COVIDseverity'][morb_df_01['COVIDseverity'] == 2] <- 1
morb_df_01$COVIDseverity <- factor(morb_df_01$COVIDseverity, c(0,1))
```


```{r group morbids}
morb_grouped <- morb_df_01 %>% 
  mutate(
    respiratory_disease = case_when(
      bronchiectasis == 1|
        pulmonary_disease == 1|
        asthma == 1|
        nasal_polyps == 1|
        hemoptysis == 1|
        pneumothorax == 1|
        resp_failure == 1|
        lung_transplant == 1~1,
      bronchiectasis == 0&
        pulmonary_disease == 0&
        asthma == 0&
        nasal_polyps == 0&
        hemoptysis == 0&
        pneumothorax == 0&
        resp_failure == 0&
        lung_transplant == 0~0),
    
    nutri_cond = case_when(
      malnutrition == 1|
        other_nutri_deficiency == 1|
        obesity == 1~1,
      malnutrition == 0&
        other_nutri_deficiency == 0&
        obesity == 0~0),
    
    diabetes = case_when(
      type1_diabetes == 1|
        type2_diabetes == 1~1,
      type1_diabetes == 0&
        type2_diabetes == 0~0),
    
    cardiac_dis = case_when(
      heart_failure == 1|
        hypertensive_heart_disease == 1|
        ischemic_heart_disease == 1|
        essential_hypertension == 1~1,
      heart_failure == 0&
        hypertensive_heart_disease == 0&
        ischemic_heart_disease == 0&
        essential_hypertension == 0~0),
      
      abdominal_cond = case_when(
        liver_disease == 1|
          other_GI_notLiver == 1|
          chronic_kidney_disease == 1~1,
        liver_disease == 0&
          other_GI_notLiver == 0&
          chronic_kidney_disease == 0~0),
    
    nicotine_dep = case_when(
      nicotine_dependence == 1~1,
      nicotine_dependence == 0~0)
    )

morb_grouped <- morb_grouped %>%
  select(1:2, 24:29)
```

```{r glm full model}
summary(glm(COVIDseverity~., family = binomial(link='logit'), 
            data = morb_grouped))
```

```{r sub_df of morb_grouops without diabetes}
no_diab_morb <- morb_grouped %>%
  select(-diabetes)
```

```{r logit model sub_df}
model_morb <-
glm(COVIDseverity~., family = binomial(link='logit'), 
            data = no_diab_morb)

summary(model_morb)
```
```{r}
a=seq(1,925952,1)
b=sample(a,740762,replace = F)
no_diab_morb_train=no_diab_morb[b,]
no_diab_morb_test=no_diab_morb[-b,]
no_diab_morb_train %>% filter(has_cf == 1) %>% count()
```

```{r}
no_diab_fitted <- glm(COVIDseverity ~ ., family = binomial(link='logit'), data = no_diab_morb_train)
```

```{r}
no_diab_predict_fit = no_diab_fitted %>% predict(no_diab_morb_test, type="response")
```

```{r}
predicted_severity2 <- ifelse(no_diab_predict_fit > 0.5, 1,0)
```

```{r}
counter=0
for(i in 1:185190)
{
  if(predicted_severity2[i] != no_diab_morb_test$COVIDseverity[i])
  {counter=counter+1}
}
counter
misclassification.rate=counter/185190
misclassification.rate
```


```{r grapg log}
ggplot(no_diab_morb_test, aes(x = respiratory_disease, y = no_diab_predict_fit)) +
  geom_boxplot(aes(fill = factor(has_cf)), alpha = 1)
```

```{r roc curve}
roc_score = roc(no_diab_morb_test$COVIDseverity, predicted_severity2)
```

```{r }
plot(roc_score, main="ROC curve -- Logistic Regression ")
```

```{r 2nd roc}
library(ROCit)
## Warning: package 'ROCit' was built under R version 3.5.2
ROCit_obj <- rocit(score=predicted_severity2,class=no_diab_morb_test$COVIDseverity)
plot(ROCit_obj)
```

