---
title: "Research-Project-BrandonH"
author: "Brandon Huett"
date: '2022-07-14'
output: html_document
---

```{r}
library(aod)
library(ggplot2)
library(mlbench)
library(caret)
library(InformationValue)
library(ISLR)
library(tidyverse)
library(ggplot2)
library(scales)
library(ROCit)
library(epitools)
library(rmeta)
library(pROC)
library(nnet)
library(ggstatsplot)
library(pander)
```

DATA FRAMES
-----------

```{r}
con_tab <- d %>% 
  select(COVIDseverity, has_cf)
```

```{r}
non_cf <- d %>%
  filter(has_cf == 0)
```

```{r}
ratetable <- con_tab %>% 
  group_by(has_cf, COVIDseverity)
```

```{r}
ratetable <- con_tab %>% 
  group_by(has_cf, COVIDseverity) %>% 
  summarize(N = n()) %>% 
  mutate(Ratio = round((N / sum(N)), 3))
```

```{r}
treat_df <- d %>% 
  select(has_cf, COVIDseverity, INOTROPES, REMDESIVIR, CCP,
         DEXAMETHASONE, ENOXAPARIN, HEPARIN, IVIG,
         METHYLPREDNISOLONE, RITUXIMAB, TOCILIZUMAB,
         ASPIRIN, LOPINAVIR_OR_RITONAVIR)
```

----------

```{r}
#contingency table, compares non-cf covid severity with race
non_cf %>% 
  group_by(COVIDseverity, encountertype) %>% 
  summarize(N = n()) %>% 
  mutate(Ratio = round(N / sum(N), 3)) %>% 
  knitr::kable()
```

```{r}
#contingency table, compares cf covid severity with encountertype
d %>% 
  group_by(COVIDseverity, encountertype) %>% 
  summarize(N = n()) %>% 
  mutate(Ratio = round(N / sum(N), 3)) %>% 
  knitr::kable()
```

```{r}
#contingency table, compares cf covid severity with encountertype
non_cf %>% 
  group_by(COVIDseverity, encountertype) %>% 
  summarize(N = n()) %>% 
  mutate(Ratio = round(N / sum(N), 3)) %>% 
  knitr::kable()
```

```{r}
#contingency table, compares covid severity between cf and non-cf
con_tab %>% 
  group_by(has_cf, COVIDseverity) %>% 
  summarize(N = n()) %>% 
  mutate(Ratio = round((N / sum(N)), 3)) %>% 
  knitr::kable()
```

```{r}
#contingency table, compares covid severity between cf and non-cf
  ratetable %>% 
  group_by(has_cf, COVIDseverity) %>% 
  summarize(N = n()) %>% 
  mutate(Ratio = round(100*(N / sum(N)), 1), "%") %>% 
  knitr::kable()
```

```{r}
#bar plot, covid severity for cf patients
ggplot(ratetable, aes(x = has_cf,
                      y = Ratio,
                      fill = COVIDseverity), position = "dodge") +
    labs(x = "Patients Without CF", 
       y = "Rate", 
       title = "COVID Severity Among Children With/Without Cystic Fibrosis") +
  geom_bar(stat = "identity")
```

```{r}
#bar plot, covid severity for non-cf patients
ggplot(non_cf) +
  geom_bar(mapping = aes(x=has_cf, fill = COVIDseverity), 
           position = 'dodge') +
  scale_y_continuous(labels = comma) +
  labs(x = "Patients Without CF", 
       y = "Count", 
       title = "COVID Severity Among Children Without Cystic Fibrosis")
```

```{r}
ggplot(con_tab) +
  geom_bar(mapping = aes(x=has_cf, fill = COVIDseverity), 
           position = 'dodge') +
  coord_cartesian(ylim = c(0, 60000)) +
  scale_y_continuous(labels = comma)
```

```{r}
  treat_df %>% 
  group_by(has_cf, COVIDseverity, INOTROPES) %>% 
  summarize(N = n()) %>% 
  mutate(Ratio = round(100*(N / sum(N)), 1), "%") %>% 
  knitr::kable()
```

Logistic Regression

```{r}
covsev01 <- d
```

```{r}
covsev01["COVIDseverity"][covsev01["COVIDseverity"] == 2] <- 1
```

```{r}
covid_data2 <- d %>% 
  select(COVIDseverity, has_cf, age_at_encounter)
```

```{r}
covid_data2["COVIDseverity"][covid_data2["COVIDseverity"] == 2] <- 1
```

```{r}
morb_df_01 <- d %>%
  select(has_cf, COVIDseverity, starts_with('comorb'))

colnames(morb_df_01) <- c('has_cf', 'COVIDseverity', 'bronchiectasis',
                        'pulmonary_disease', 'asthma', 'nasal_polyps',
                        'hemoptysis', 'pneumothorax', 'resp_failure', 
                        'malnutrition', 'other_nutri_deficiency', 
                        'type1_diabetes', 'type2_diabetes', 'obesity', 
                        'liver_disease', 'other_GI_notLiver', 
                        'essential_hypertension', 'hypertensive_heart_disease',
                        'chronic_kidney_disease', 'nicotine_dependence', 
                        'heart_failure', 'ischemic_heart_disease', 
                        'lung_transplant')

```

```{r}
#table with severity, cf and comorbidities NOTE: Changed names for readability
morb_df <- d %>%
  select(has_cf, COVIDseverity, starts_with('comorb'))


colnames(morb_df) <- c('has_cf', 'COVIDseverity', 'bronchiectasis',
                        'pulmonary_disease', 'asthma', 'nasal_polyps',
                        'hemoptysis', 'pneumothorax', 'resp_failure', 
                        'malnutrition', 'other_nutri_deficiency', 
                        'type1_diabetes', 'type2_diabetes', 'obesity', 
                        'liver_disease', 'other_GI_notLiver', 
                        'essential_hypertension', 'hypertensive_heart_disease',
                        'chronic_kidney_disease', 'nicotine_dependence', 
                        'heart_failure', 'ischemic_heart_disease', 
                        'lung_transplant')
```

```{r}
#created altered data frame of morb_df to have severity to two levels
morb_df_01 <- morb_df
morb_df_01['COVIDseverity'][morb_df_01['COVIDseverity'] == 2] <- 1

morb_df_01$COVIDseverity <- factor(morb_df_01$COVIDseverity, c(0,1))
```

```{r}
#assigns morb_df_01 to morb_grouped
morb_grouped <- morb_df_01
```

```{r}
#creates 6 groups within dataframe for morbidities
morb_grouped <- morb_df_01 %>% 
  mutate(
    respiratory_disease = case_when(
      bronchiectasis == 1|
        pulmonary_disease == 1|
        asthma == 1|
        nasal_polyps == 1|
        hemoptysis == 1|
        pneumothorax == 1|
        resp_failure == 1|
        lung_transplant == 1~1,
      bronchiectasis == 0&
        pulmonary_disease == 0&
        asthma == 0&
        nasal_polyps == 0&
        hemoptysis == 0&
        pneumothorax == 0&
        resp_failure == 0&
        lung_transplant == 0~0),
    
    nutri_cond = case_when(
      malnutrition == 1|
        other_nutri_deficiency == 1|
        obesity == 1~1,
      malnutrition == 0&
        other_nutri_deficiency == 0&
        obesity == 0~0),
    
    diabetes = case_when(
      type1_diabetes == 1|
        type2_diabetes == 1~1,
      type1_diabetes == 0&
        type2_diabetes == 0~0),
    
    cardiac_dis = case_when(
      heart_failure == 1|
        hypertensive_heart_disease == 1|
        ischemic_heart_disease == 1|
        essential_hypertension == 1~1,
      heart_failure == 0&
        hypertensive_heart_disease == 0&
        ischemic_heart_disease == 0&
        essential_hypertension == 0~0),
      
      abdominal_cond = case_when(
        liver_disease == 1|
          other_GI_notLiver == 1|
          chronic_kidney_disease == 1~1,
        liver_disease == 0&
          other_GI_notLiver == 0&
          chronic_kidney_disease == 0~0),
    
      nicotine_dep = case_when(
        nicotine_dependence == 1~1,
        nicotine_dependence == 0~0)
    )
```

```{r}
#code for selecting specific columns
morb_grouped <- morb_grouped %>% 
  select(1:2, 24:29)
```

```{r}
glm_morb <- (glm(COVIDseverity~., family = binomial(link='logit'), 
            data = morb_grouped))
```

```{r sub_df of morb_grouops without diabetes}
no_diab_morb <- morb_grouped %>%
  select(-diabetes)
```

```{r}
a=seq(1,925952,1)
b=sample(a,740762,replace = F)
no_diab_morb_train=no_diab_morb[b,]
no_diab_morb_test=no_diab_morb[-b,]
no_diab_morb_train %>% filter(has_cf == 1) %>% count()
```

```{r glm full model}
summary(glm(COVIDseverity~., family = binomial(link='logit'), 
            data = morb_grouped))
```

```{r logit model sub_df}
model_morb <-
glm(COVIDseverity~., family = binomial(link='logit'), 
            data = no_diab_morb)

summary(model_morb)
```

```{r}
a=seq(1,925952,1)
b=sample(a,740762,replace = F)
no_diab_morb_train=no_diab_morb[b,]
no_diab_morb_test=no_diab_morb[-b,]
no_diab_morb_train %>% filter(has_cf == 1) %>% count()
```

```{r}
no_diab_fitted <- glm(COVIDseverity ~ ., family = binomial(link='logit'), data = no_diab_morb_train)
```

```{r}
no_diab_predict_fit = no_diab_fitted %>% predict(no_diab_morb_test, type="response")
```

```{r}
predicted_severity2 <- ifelse(no_diab_predict_fit > 0.5, 1,0)
```

```{r}
counter=0
for(i in 1:185190)
{
  if(predicted_severity2[i] != no_diab_morb_test$COVIDseverity[i])
  {counter=counter+1}
}
counter
misclassification.rate=counter/185190
misclassification.rate
```

```{r}
no_diab_fitted$coef
```

```{r}
summary(no_diab_fitted)
pander::pander(no_diab_fitted)
```


```{r}
b0 <- no_diab_fitted$coef[1]
X1 <- no_diab_fitted$coef[2]

```

